version: '3.3'
services:
  frontend:
    env_file:
      - env-aggregator.env
  backend:
    depends_on:
      - db
    env_file:
      - env-postgres.env
      - env-backend.env
      - env-aggregator.env
  db:
    image: postgres:11
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - env-pgadmin.env
  proxy:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    environment:
      - DOMAIN=${DOMAIN}
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
