version: '3.3'
services:
  backend:
    depends_on:
      - db
    env_file:
      - env-postgres.env
      - env-backend.env
  celeryworker:
    depends_on:
      - db
      - queue
    env_file:
      - env-postgres.env
      - env-backend.env
  db:
    image: postgres:11
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - env-pgadmin.env
  proxy:
    image: nginx:stable-alpine
    depends_on:
      - backend
      - frontend
    environment:
      - DOMAIN=${DOMAIN}
      - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES}
      - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS}
  flower:
    image: mher/flower
    env_file:
      - env-flower.env
    command:
      - "--broker=amqp://guest@queue:5672//"
      - "--broker_api=http://guest:guest@queue:15672/api//"
  queue:
    image: rabbitmq:3-management
