version: '3.3'
services:
  backend:
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  frontend:
    environment:
      - SERVER_HOST=https://${DOMAIN}
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
  proxy:
    command: sh -c "
        envsubst '$$DOMAIN' < /etc/nginx/conf.d/nginx.deploy.template > /etc/nginx/conf.d/default.conf
        && sed -i '/worker_processes\s/c\worker_processes ${NGINX_WORKER_PROCESSES};' /etc/nginx/nginx.conf
        && sed -i '/worker_connections\s/c\worker_connections ${NGINX_WORKER_CONNECTIONS};' /etc/nginx/nginx.conf
        && exec nginx-debug -g 'daemon off;'
      "
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.deploy.template:/etc/nginx/conf.d/nginx.deploy.template:ro'
      - '/etc/letsencrypt:/etc/letsencrypt:ro'
      - '/var/www/letsencrypt:/var/www/letsencrypt:ro'
    restart: always

volumes:
  app-db-data: