version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        env: dev
    command: /start-reload.sh
    environment:
      - 'JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root'
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=http://${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}
    ports:
      - '8888:8888'
    volumes:
      - ./backend/app:/app
  backend-tests:
    build:
      context: ./backend
      dockerfile: tests.dockerfile
      args:
        env: dev
    environment:
      - JUPYTER=jupyter notebook --ip=0.0.0.0 --allow-root
    volumes:
      - ./backend/app:/app
  frontend:
    build:
      context: ./frontend
    environment:
      - SERVER_HOST=http://${DOMAIN}
    ports:
      - '5555:5555'
  proxy:
    command: sh -c "
      envsubst '$$DOMAIN' < /etc/nginx/conf.d/nginx.dev.template > /etc/nginx/conf.d/default.conf
      && sed -i '/worker_processes\s/c\worker_processes ${NGINX_WORKER_PROCESSES};' /etc/nginx/nginx.conf
      && sed -i '/worker_connections\s/c\worker_connections ${NGINX_WORKER_CONNECTIONS};' /etc/nginx/nginx.conf
      && exec nginx-debug -g 'daemon off;'
      "
    ports:
      - '80:80'
    volumes:
      - ./nginx.dev.template:/etc/nginx/conf.d/nginx.dev.template
  pgadmin:
    ports:
      - '5050:5050'