"""Add auth_error column to Farm model

Revision ID: 470c328a5792
Revises: 01dce80b014b
Create Date: 2020-01-02 23:46:59.800246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470c328a5792'
down_revision = '01dce80b014b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('auth_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'auth_error')
    # ### end Alembic commands ###
