"""Add FarmToken table and is_authorized column to Farm

Revision ID: 64749ec93c4c
Revises: 5bac0b729b20
Create Date: 2019-10-30 15:45:30.264336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64749ec93c4c'
down_revision = '5bac0b729b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_in', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id')
    )
    op.add_column('farm', sa.Column('is_authorized', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'is_authorized')
    op.drop_table('farmtoken')
    # ### end Alembic commands ###
