"""Add last_accessed column to Farm model

Revision ID: 67a92a0fca4e
Revises: 64749ec93c4c
Create Date: 2019-11-23 00:20:47.947002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a92a0fca4e'
down_revision = '64749ec93c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'last_accessed')
    # ### end Alembic commands ###
