"""Add test field to user model

Revision ID: 8ddb2bd45bd1
Revises: cd672c4e6bda
Create Date: 2020-03-05 20:01:02.127427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddb2bd45bd1'
down_revision = 'cd672c4e6bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_update', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_update')
    # ### end Alembic commands ###
