"""Add info column to Farm model

Revision ID: c717af8cff85
Revises: 67a92a0fca4e
Create Date: 2019-12-19 21:54:35.047143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c717af8cff85'
down_revision = '67a92a0fca4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm', sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farm', 'info')
    # ### end Alembic commands ###
