"""Add indexes to farm_token

Revision ID: d2422b5a6859
Revises: 90a5fd6c8be7
Create Date: 2020-05-21 15:46:17.852847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d2422b5a6859"
down_revision = "90a5fd6c8be7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_farmtoken_farm_id"), "farmtoken", ["farm_id"], unique=True)
    op.create_index(op.f("ix_farmtoken_id"), "farmtoken", ["id"], unique=False)
    op.drop_constraint("farmtoken_farm_id_key", "farmtoken", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("farmtoken_farm_id_key", "farmtoken", ["farm_id"])
    op.drop_index(op.f("ix_farmtoken_id"), table_name="farmtoken")
    op.drop_index(op.f("ix_farmtoken_farm_id"), table_name="farmtoken")
    # ### end Alembic commands ###
